%YAML:1.0

#common parameters

tf_topic: "/tf"     # tf topic
pose_topic: "/vrpn_client_node/aliendog/pose"  # pose topic
twist_topic: "/vrpn_client_node/aliendog/twist"  # twist topic       

imu_topic: "/aliengo/imu"

output_path: "/home/ray/Documents/Ros_project/ilo/src/go/output"

num_of_leg: 4    # 腿的数量
leg_topic: "/aliengo/joint_states"  # 腿部关节数据topic

leg_offset_x: 0.2407
leg_offset_y: 0.051
thigh_offset: 0.0868
thigh_length: 0.25
calf_length: 0.25
